[project]
name = "rdkit-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=6.0.2",
    "seaborn>=0.13.2",
    "squarify>=0.4.4",
]
